obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  device_info/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  project_info/
obj-$(CONFIG_RECORD_MDMRST)	+=  mdmrst/
obj-$(CONFIG_OPPO_HYPNUS)     +=  oppo_hypnus/
obj-y +=  oppo_als_cali_value/

