obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

#ifdef VENDOR_EDIT
#/* Yichun.Chen  PSW.BSP.CHG  2019- */
obj-$(CONFIG_OPPO_SM7150_CHARGER)	+= oppo/
#endif